### PR TITLE
Built majority of website

### PR DESCRIPTION
**Pull request by jordanhilado**
- Added custom logo and favicon
- Changed website content to describe the product
- Added GitHub repo and documentation links
- Added demo page for user to test search querys (needs backend implementation)
- Added placeholder images and gifs
- Fixed header and footers

### CODE REVIEW

**Comment by jordanhilado** [comment]
Not sure why deploy to firebase hosting failed, but it should work if build folder is recreated once pushed to main.

**Comment by ayushmaang** [comment]
There are a lot of file changes in this commit. Could you highlight the main files to look at and add some screen shots of the website? Perhaps also host it on firebase?

**Comment by jordanhilado** [comment]
I have Firebase hosting set up so that it deploys onto the actual site once it is merged into main.

Important files:
- App.js + index.js (src)
- Home.js (src > views)
- LayoutDefault.js (src > layouts)
- Footer.js + Header.js (src > components > layout)
- Hero.js + Demo.js + FeaturesSplit.js + FeaturesTiles.js (src > components > sections)
Screen Shot 2021-08-06 at 2 57 27 PM
Screen Shot 2021-08-06 at 2 57 33 PM
Screen Shot 2021-08-06 at 2 57 38 PM
Screen Shot 2021-08-06 at 2 57 41 PM
Screen Shot 2021-08-06 at 2 57 47 PM

**Review by ayushmaang — COMMENTED** [review]
Delete the node_modules folder in this push.

**Review by ayushmaang — APPROVED** [review]
Looks good now.

**Pull request merged**
